#goal definition
string ObjectType #"Cart", "Elevator" or "Charger"
string Mode # "DOCK" or "UNDOCK"
float32 BeaconDistance
float32 offsetDistance
geometry_msgs/PoseStamped Pose
---
#result definition
int32 percentage
string skillStatus
---
#feedback
int32 percentage
string skillStatus
