#goal definition
string Direction #FORWARD, BACKWARDS, RIGHT, LEFT
float32 Distance
bool Start
bool End
---
#result definition
int32 percentage
string skillStatus
---
#feedback
int32 percentage
string skillStatus
